### ISSUE TITLE
validation fails

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#21]
Following the documentation at https://pynwb.readthedocs.io/en/stable/validation.html :
Similar to https://github.com/NeurodataWithoutBorders/pynwb/issues/1058

The validation below fails:
`python -m pynwb.validate file_with_extension.nwb`

**Comment by oruebel** [comment]
Running the validator as part of the simple example notebook https://github.com/oruebel/ndx-icephys-meta/blob/master/src/pynwb/examples/icephys_meta_simple_example.ipynb yields the following error. The validator seems to complain about "'Device' - cannot overwrite existing specification" but the extension does not actually extend Device. I'm not sure right now why this is failing, but I figures having the error and a test to run may at least help us get closer to the source of the issue.


```
Traceback (most recent call last):
  File "/Users/oruebel/anaconda3/envs/py4nwb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/oruebel/anaconda3/envs/py4nwb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/oruebel/Devel/nwb/pynwb/src/pynwb/validate.py", line 126, in <module>
    main()
  File "/Users/oruebel/Devel/nwb/pynwb/src/pynwb/validate.py", line 72, in main
    ns_deps = NWBHDF5IO.load_namespaces(catalog, path)
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 126, in load_namespaces
    d.update(namespace_catalog.load_namespaces('namespace', reader=reader))
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/namespace.py", line 466, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/namespace.py", line 407, in __load_namespace
    self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/namespace.py", line 375, in __load_spec_file
    ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/namespace.py", line 365, in __reg_spec
    return catalog.auto_register(spec_obj, spec_source)
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/catalog.py", line 101, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/catalog.py", line 101, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/catalog.py", line 101, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/catalog.py", line 92, in auto_register
    self.register_spec(spec, source_file)
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/oruebel/Devel/nwb/hdmf/src/hdmf/spec/catalog.py", line 45, in register_spec
    raise ValueError("'%s' - cannot overwrite existing specification" % type_name)
ValueError: 'Device' - cannot overwrite existing specification
```

**Comment by oruebel** [comment]
@t-b you have been working on the validator more than I have. Do you have any idea what the problem may be? CC @rly  ideas?

**Comment by oruebel** [comment]
Closed in favor of https://github.com/hdmf-dev/hdmf/issues/316 which should fix this issue.

**Comment by oruebel** [comment]
See also https://github.com/NeurodataWithoutBorders/nwb-schema/pull/421
